import type { Kit, Plan } from "@schemas/index";

export const renderSupplementationPlanPdf = async (plan: Plan, kits: Kit[]): Promise<Buffer> => {
  const lines = [
    `Supplementation plan for ${plan.eventId}`,
    `Chosen variant: ${plan.chosenVariant}`,
    '',
    'Kit summary:',
    ...kits.map((kit) => `${kit.variant.toUpperCase()} - $${kit.totalPrice.toFixed(2)} (${kit.totalWeightGrams} g)`),
    '',
    'Generated by Athletic Fuel',
  ];

  return Buffer.from(lines.join("\n"), 'utf-8');
};
